#include "PluginEditor.h"
#include <array>
#include <cmath>
void PedalLookAndFeel::drawRotarySlider(juce::Graphics&g,int x,int y,int w,int h,float p,float a0,float a1,juce::Slider&){auto r=juce::Rectangle<float>((float)x,(float)y,(float)w,(float)h).reduced(9);float s=juce::jmin(r.getWidth(),r.getHeight());r=r.withSizeKeepingCentre(s,s);auto c=r.getCentre();g.setColour(juce::Colours::black.withAlpha(.35f));g.fillEllipse(r.translated(4,6));juce::ColourGradient q(juce::Colour(0xff4d4d4d),r.getX(),r.getY(),juce::Colours::black,r.getRight(),r.getBottom(),false);g.setGradientFill(q);g.fillEllipse(r);g.setColour(juce::Colour(0xff090909));g.drawEllipse(r,3);auto hub=r.reduced(s*.29f);juce::ColourGradient m(juce::Colour(0xffeeeeea),hub.getX(),hub.getY(),juce::Colour(0xff777773),hub.getRight(),hub.getBottom(),false);g.setGradientFill(m);g.fillEllipse(hub);float an=a0+p*(a1-a0),rad=s*.43f;juce::Path z;z.addRoundedRectangle(-2,-rad,4,rad*.44f,2);g.setColour(juce::Colours::white);g.fillPath(z,juce::AffineTransform::rotation(an).translated(c.x,c.y));}
void PedalLookAndFeel::drawButtonBackground(juce::Graphics&g,juce::Button&b,const juce::Colour&,bool over,bool down){auto r=b.getLocalBounds().toFloat().reduced(1);g.setColour(down?juce::Colour(0xffff7a19):over?juce::Colour(0xff3a3a3a):juce::Colour(0xff171717));g.fillRoundedRectangle(r,5);g.setColour(juce::Colour(0xff777777));g.drawRoundedRectangle(r,5,1);}
void MeterArc::paint(juce::Graphics&g){auto r=getLocalBounds().toFloat();auto c=r.getCentre();float rad=juce::jmin(r.getWidth(),r.getHeight())*.46f;for(int i=0;i<20;++i){float t=i/19.f,a=juce::MathConstants<float>::pi*(1.14f+.72f*t);auto col=t<.5f?juce::Colour(0xff33ef52):t<.7f?juce::Colour(0xffffe029):t<.86f?juce::Colour(0xffff8a18):juce::Colour(0xffff2525);auto pt=c+juce::Point<float>(std::cos(a),std::sin(a))*rad;bool on=t<=level;g.setColour(on?col:juce::Colours::black.withAlpha(.28f));g.fillEllipse(pt.x-5,pt.y-5,10,10);}}
PERCULATORAudioProcessorEditor::PERCULATORAudioProcessorEditor(PERCULATORAudioProcessor&p):AudioProcessorEditor(&p),processor(p){setLookAndFeel(&look);setResizable(true,true);setResizeLimits(1000,620,1600,992);getConstrainer()->setFixedAspectRatio(1.6129);setSize(1300,806);knob(harmonics,harmonicsL,"HARMONICS","");knob(balance,balanceL,"BALANCE","");knob(input,inputL,"INPUT"," dB");knob(bias,biasL,"BIAS"," %");knob(mix,mixL,"MIX"," %");knob(output,outputL,"OUTPUT"," dB");knob(irMix,irMixL,"IR MIX"," %");knob(irLevel,irLevelL,"IR LEVEL"," dB");knob(circuit,circuitL,"CIRCUIT","");circuit.setNumDecimalPlacesToDisplay(0);circuit.textFromValueFunction=[](double v){return juce::StringArray{"NPN OD","D310 Diodes","Albino"}[juce::jlimit(0,2,juce::roundToInt(v))];};addAndMakeVisible(loadIR);addAndMakeVisible(prevIR);addAndMakeVisible(nextIR);addAndMakeVisible(irOn);addAndMakeVisible(phase);addAndMakeVisible(bypass);addAndMakeVisible(irLabel);addAndMakeVisible(colourBox);addAndMakeVisible(oversamplingBox);addAndMakeVisible(inputMeter);addAndMakeVisible(outputMeter);irLabel.setText(processor.getIRName(),juce::dontSendNotification);irLabel.setJustificationType(juce::Justification::centredLeft);irLabel.setColour(juce::Label::backgroundColourId,juce::Colour(0xff111111));irLabel.setColour(juce::Label::textColourId,juce::Colour(0xffdddddd));colourBox.addItem("Dictatorship",1);colourBox.addItem("Surf Party",2);colourBox.addItem("Fetish Red",3);colourBox.setSelectedId(processor.getPanelColourIndex()+1);colourBox.onChange=[this]{processor.setPanelColourIndex(colourBox.getSelectedId()-1);repaint();};oversamplingBox.addItemList({"2x","4x","8x"},1);loadIR.onClick=[this]{chooseIR();};aH=std::make_unique<SA>(p.apvts,"harmonics",harmonics);aB=std::make_unique<SA>(p.apvts,"balance",balance);aI=std::make_unique<SA>(p.apvts,"input",input);aBi=std::make_unique<SA>(p.apvts,"bias",bias);aM=std::make_unique<SA>(p.apvts,"mix",mix);aO=std::make_unique<SA>(p.apvts,"output",output);aIM=std::make_unique<SA>(p.apvts,"irmix",irMix);aIL=std::make_unique<SA>(p.apvts,"irlevel",irLevel);aC=std::make_unique<SA>(p.apvts,"circuit",circuit);aIO=std::make_unique<BA>(p.apvts,"iron",irOn);aP=std::make_unique<BA>(p.apvts,"phase",phase);aBy=std::make_unique<BA>(p.apvts,"bypass",bypass);aOS=std::make_unique<CA>(p.apvts,"oversampling",oversamplingBox);startTimerHz(30);}
PERCULATORAudioProcessorEditor::~PERCULATORAudioProcessorEditor(){setLookAndFeel(nullptr);}void PERCULATORAudioProcessorEditor::knob(juce::Slider&s,juce::Label&l,const juce::String&t,const juce::String&u){addAndMakeVisible(s);s.setSliderStyle(juce::Slider::RotaryHorizontalVerticalDrag);s.setTextBoxStyle(juce::Slider::TextBoxBelow,false,96,22);s.setTextValueSuffix(u);addAndMakeVisible(l);l.setText(t,juce::dontSendNotification);l.setJustificationType(juce::Justification::centred);l.setFont(juce::FontOptions(17,juce::Font::bold));}
juce::Colour PERCULATORAudioProcessorEditor::panel() const
{
    static const std::array<juce::Colour, 3> colours
    {
        juce::Colour (0xff657448),
        juce::Colour (0xff91d9b9),
        juce::Colour (0xffbd171d)
    };

    const auto index = static_cast<size_t> (
        juce::jlimit (0, 2, processor.getPanelColourIndex()));

    return colours[index];
}
void PERCULATORAudioProcessorEditor::paint(juce::Graphics&g){g.fillAll(juce::Colour(0xff0d0e0e));auto p=getLocalBounds().reduced(18).withTrimmedTop(46).withTrimmedBottom(42).toFloat();juce::ColourGradient gr(panel().brighter(.16f),p.getX(),p.getY(),panel().darker(.22f),p.getRight(),p.getBottom(),false);g.setGradientFill(gr);g.fillRoundedRectangle(p,18);g.setColour(juce::Colours::black);g.drawRoundedRectangle(p,18,4);for(auto pt:{p.getTopLeft()+juce::Point<float>(22,22),p.getTopRight()+juce::Point<float>(-22,22),p.getBottomLeft()+juce::Point<float>(22,-22),p.getBottomRight()+juce::Point<float>(-22,-22)}){g.setColour(juce::Colour(0xffbdbdb8));g.fillEllipse(pt.x-7,pt.y-7,14,14);g.setColour(juce::Colours::black);g.drawLine(pt.x-4,pt.y,pt.x+4,pt.y,1.5f);}auto ir=juce::Rectangle<float>(getWidth()*.705f,100,getWidth()*.25f,330);g.setColour(juce::Colours::black.withAlpha(.18f));g.fillRoundedRectangle(ir,12);g.setColour(juce::Colours::black.withAlpha(.7f));g.drawRoundedRectangle(ir,12,2);g.setColour(juce::Colours::black);g.setFont(juce::FontOptions(50,juce::Font::bold));g.drawText("PERCULATOR",50,getHeight()-155,500,60,juce::Justification::centredLeft);g.setFont(juce::FontOptions(16,juce::Font::bold));g.drawText("DUAL POLARITY HARMONIC GENERATOR",53,getHeight()-98,460,25,juce::Justification::centredLeft);g.setFont(juce::FontOptions(22,juce::Font::bold));g.drawText("CABINET IR",(int)ir.getX(),70,(int)ir.getWidth(),28,juce::Justification::centred);g.setColour(juce::Colours::white);g.setFont(juce::FontOptions(13));g.drawText("PANEL COLOR",25,12,105,25,juce::Justification::centredLeft);g.drawText("v0.3.0 alpha",28,getHeight()-33,110,20,juce::Justification::centredLeft);}
void PERCULATORAudioProcessorEditor::resized(){float x=getWidth()/1300.f,y=getHeight()/806.f;auto R=[x,y](int a,int b,int c,int d){return juce::Rectangle<int>((int)(a*x),(int)(b*y),(int)(c*x),(int)(d*y));};colourBox.setBounds(R(130,9,155,30));harmonicsL.setBounds(R(105,85,210,28));harmonics.setBounds(R(105,112,210,215));balanceL.setBounds(R(450,85,210,28));balance.setBounds(R(450,112,210,215));inputL.setBounds(R(80,348,150,26));input.setBounds(R(78,375,155,165));inputMeter.setBounds(R(62,354,186,160));biasL.setBounds(R(255,348,150,26));bias.setBounds(R(253,375,155,165));mixL.setBounds(R(430,348,150,26));mix.setBounds(R(428,375,155,165));outputL.setBounds(R(605,348,150,26));output.setBounds(R(603,375,155,165));outputMeter.setBounds(R(587,354,186,160));irLabel.setBounds(R(925,125,270,46));irOn.setBounds(R(845,128,75,36));prevIR.setBounds(R(925,180,49,32));nextIR.setBounds(R(979,180,49,32));loadIR.setBounds(R(1035,180,160,32));irMixL.setBounds(R(860,235,130,25));irMix.setBounds(R(850,260,145,150));irLevelL.setBounds(R(1010,235,130,25));irLevel.setBounds(R(1000,260,145,150));phase.setBounds(R(1150,280,70,38));bypass.setBounds(R(1150,350,80,42));oversamplingBox.setBounds(R(1000,455,105,30));circuitL.setBounds(R(930,555,220,26));circuit.setBounds(R(950,580,180,180));}
void PERCULATORAudioProcessorEditor::timerCallback(){inputMeter.setLevel(processor.getInputMeter());outputMeter.setLevel(processor.getOutputMeter());if(irLabel.getText()!=processor.getIRName())irLabel.setText(processor.getIRName(),juce::dontSendNotification);}bool PERCULATORAudioProcessorEditor::isInterestedInFileDrag(const juce::StringArray&f){return f.size()==1&&juce::File(f[0]).hasFileExtension("wav;aif;aiff;flac");}void PERCULATORAudioProcessorEditor::filesDropped(const juce::StringArray&f,int,int){if(!f.isEmpty())processor.loadImpulseResponse(juce::File(f[0]));}void PERCULATORAudioProcessorEditor::chooseIR(){chooser=std::make_unique<juce::FileChooser>("Load cabinet IR",juce::File{},"*.wav;*.aif;*.aiff;*.flac");chooser->launchAsync(juce::FileBrowserComponent::openMode|juce::FileBrowserComponent::canSelectFiles,[this](const juce::FileChooser&f){auto r=f.getResult();if(r.existsAsFile())processor.loadImpulseResponse(r);});}
